### ISSUE TITLE
"make" Command Errors

### ISSUE THREAD

**Issue by dodsonbryan** [brettbode/wxmacmolplt#98]
### Please describe the problem or enhancement:
Making all in src
make[1]: Entering directory '.../Downloads/wxmacmolplt-7.6.2/src'
g++ -DPACKAGE_NAME=\"wxmacmolplt\" -DPACKAGE_TARNAME=\"wxmacmolplt\" -DPACKAGE_VERSION=\"7.6.2\" -DPACKAGE_STRING=\"wxmacmolplt\ 7.6.2\" -DPACKAGE_BUGREPORT=\"MMP.Guy@gmail.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"wxmacmolplt\" -DVERSION=\"7.6.2\" -I.    -I/usr/local/lib/wx/include/gtk3-unicode-3.1 -I/usr/local/include/wx-3.1 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -DINSTALL_PREFIX=\"NONE\" -g -O2 -MT bondsdlg.o -MD -MP -MF .deps/bondsdlg.Tpo -c -o bondsdlg.o bondsdlg.cpp
bondsdlg.cpp:59:34: error: invalid use of non-static member function ‘void BondsDlg::OnCellChange(wxGridEvent&)’
  EVT_GRID_CELL_CHANGE( BondsDlg::OnCellChange )
                                  ^
bondsdlg.cpp:59:47: error: ‘EVT_GRID_CELL_CHANGE’ was not declared in this scope
  EVT_GRID_CELL_CHANGE( BondsDlg::OnCellChange )
                                               ^
In file included from /usr/local/include/wx-3.1/wx/wx.h:24:0,
                 from mmp_gl.h:9,
                 from Globals.h:36,
                 from bondsdlg.cpp:14:
/usr/local/include/wx-3.1/wx/event.h:90:5: error: expected ‘}’ before ‘wxEventTableEntry’
     wxEventTableEntry(type, winid, idLast, wxNewEventTableFunctor(type, fn), ob
     ^
/usr/local/include/wx-3.1/wx/event.h:4126:5: note: in expansion of macro ‘wxDECLARE_EVENT_TABLE_ENTRY’
     wxDECLARE_EVENT_TABLE_ENTRY(evt, id1, id2, fn, NULL),
     ^
/usr/local/include/wx-3.1/wx/event.h:4128:5: note: in expansion of macro ‘wx__DECLARE_EVT2’
     wx__DECLARE_EVT2(evt, id, wxID_ANY, fn)
     ^
/usr/local/include/wx-3.1/wx/generic/grid.h:2659:5: note: in expansion of macro ‘wx__DECLARE_EVT1’
     wx__DECLARE_EVT1(wxEVT_GRID_ ## evt, id, wxGridEventHandler(fn))
     ^
/usr/local/include/wx-3.1/wx/generic/grid.h:2686:50: note: in expansion of macro ‘wx__DECLARE_GRIDEVT’
 #define EVT_GRID_CMD_SELECT_CELL(id, fn)         wx__DECLARE_GRIDEVT(SELECT_CEL
                                                  ^
/usr/local/include/wx-3.1/wx/generic/grid.h:2711:42: note: in expansion of macro ‘EVT_GRID_CMD_SELECT_CELL’
 #define EVT_GRID_SELECT_CELL(fn)         EVT_GRID_CMD_SELECT_CELL(wxID_ANY, fn)
                                          ^
bondsdlg.cpp:60:2: note: in expansion of macro ‘EVT_GRID_SELECT_CELL’
  EVT_GRID_SELECT_CELL( BondsDlg::OnSelectCell )
  ^
/usr/local/include/wx-3.1/wx/event.h:90:5: error: expected ‘,’ or ‘;’ before ‘wxEventTableEntry’
     wxEventTableEntry(type, winid, idLast, wxNewEventTableFunctor(type, fn), ob
     ^
/usr/local/include/wx-3.1/wx/event.h:4126:5: note: in expansion of macro ‘wxDECLARE_EVENT_TABLE_ENTRY’
     wxDECLARE_EVENT_TABLE_ENTRY(evt, id1, id2, fn, NULL),
     ^
/usr/local/include/wx-3.1/wx/event.h:4128:5: note: in expansion of macro ‘wx__DECLARE_EVT2’
     wx__DECLARE_EVT2(evt, id, wxID_ANY, fn)
     ^
/usr/local/include/wx-3.1/wx/generic/grid.h:2659:5: note: in expansion of macro ‘wx__DECLARE_EVT1’
     wx__DECLARE_EVT1(wxEVT_GRID_ ## evt, id, wxGridEventHandler(fn))
     ^
/usr/local/include/wx-3.1/wx/generic/grid.h:2686:50: note: in expansion of macro ‘wx__DECLARE_GRIDEVT’
 #define EVT_GRID_CMD_SELECT_CELL(id, fn)         wx__DECLARE_GRIDEVT(SELECT_CEL
                                                  ^
/usr/local/include/wx-3.1/wx/generic/grid.h:2711:42: note: in expansion of macro ‘EVT_GRID_CMD_SELECT_CELL’
 #define EVT_GRID_SELECT_CELL(fn)         EVT_GRID_CMD_SELECT_CELL(wxID_ANY, fn)
                                          ^
bondsdlg.cpp:60:2: note: in expansion of macro ‘EVT_GRID_SELECT_CELL’
  EVT_GRID_SELECT_CELL( BondsDlg::OnSelectCell )
  ^
In file included from /usr/local/include/wx-3.1/wx/wx.h:24:0,
                 from mmp_gl.h:9,
                 from Globals.h:36,
                 from bondsdlg.cpp:14:
/usr/local/include/wx-3.1/wx/event.h:4112:40: error: expected declaration before ‘}’ token
     wxDECLARE_EVENT_TABLE_TERMINATOR() };
                                        ^
/usr/local/include/wx-3.1/wx/event.h:4414:56: note: in expansion of macro ‘wxEND_EVENT_TABLE’
 #define END_EVENT_TABLE()                              wxEND_EVENT_TABLE()
                                                        ^
bondsdlg.cpp:65:1: note: in expansion of macro ‘END_EVENT_TABLE’
 END_EVENT_TABLE()
 ^
Makefile:541: recipe for target 'bondsdlg.o' failed
make[1]: *** [bondsdlg.o] Error 1
make[1]: Leaving directory '/home/cowcow/Downloads/wxmacmolplt-7.6.2/src'
Makefile:570: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

### If this is a bug report please list the steps required to reproduce the problem:
./configure step then make
### What version are you running?
Newest (wxMacMolPlt-7.6.2)
### What OS are you using? (please include 32/64 bit and if Linux the specific distribution)
Ubuntu 16.04, 64 bit

**Comment by brettbode** [comment]
Hello,
  I will take a look at this next week. I likely have the issue resolved in my devel branch. Did you try building against the Ubuntu wx3.0 packages?

Best,
Brett

**Comment by dodsonbryan** [comment]
I have wxWidgets-3.1.0 installed, currently. Should I delete this and only work with wxWidgets 3.0? I do not know if that is causing the specific problem, for other programs have shown a similar error type when compiling them (unrelated to wxWidgets-3.x). I am running the newest program versions of all products, to the best of my knowledge (either provided by the vendor, via apt-get or on their website, as the case was for wxWidgets).

**Comment by brettbode** [comment]
Is that an Ubuntu supplied wx 3.1 or one you built from source? If you built it from source try grabbing the Ubuntu 3.0 package (just grab the wx devel package and it will pull the rest). If you leave off the wx path when configuring MacMolPlt it should pick the system (/usr/include...) version. Otherwise I can also roll up a prerelease tarball and have you try that. I am building against 3.1 regularly on my dev system so am pretty confident that would work.

Brett

**Comment by dodsonbryan** [comment]
I had built it from source, here is a list of files that are located in my /usr/local/lib folder; libwx_baseu-3.1.so             libwx_gtk3u_html-3.1.so.0.0.0
libwx_baseu-3.1.so.0           libwx_gtk3u_propgrid-3.1.so
libwx_baseu-3.1.so.0.0.0       libwx_gtk3u_propgrid-3.1.so.0
libwx_baseu_net-3.1.so         libwx_gtk3u_propgrid-3.1.so.0.0.0
libwx_baseu_net-3.1.so.0       libwx_gtk3u_qa-3.1.so
libwx_baseu_net-3.1.so.0.0.0   libwx_gtk3u_qa-3.1.so.0
libwx_baseu_xml-3.1.so         libwx_gtk3u_qa-3.1.so.0.0.0
libwx_baseu_xml-3.1.so.0       libwx_gtk3u_ribbon-3.1.so
libwx_baseu_xml-3.1.so.0.0.0   libwx_gtk3u_ribbon-3.1.so.0
libwx_gtk3u_adv-3.1.so         libwx_gtk3u_ribbon-3.1.so.0.0.0
libwx_gtk3u_adv-3.1.so.0       libwx_gtk3u_richtext-3.1.so
libwx_gtk3u_adv-3.1.so.0.0.0   libwx_gtk3u_richtext-3.1.so.0
libwx_gtk3u_aui-3.1.so         libwx_gtk3u_richtext-3.1.so.0.0.0
libwx_gtk3u_aui-3.1.so.0       libwx_gtk3u_stc-3.1.so
libwx_gtk3u_aui-3.1.so.0.0.0   libwx_gtk3u_stc-3.1.so.0
libwx_gtk3u_core-3.1.so        libwx_gtk3u_stc-3.1.so.0.0.0
libwx_gtk3u_core-3.1.so.0      libwx_gtk3u_xrc-3.1.so
libwx_gtk3u_core-3.1.so.0.0.0  libwx_gtk3u_xrc-3.1.so.0
libwx_gtk3u_gl-3.1.so          libwx_gtk3u_xrc-3.1.so.0.0.0
libwx_gtk3u_gl-3.1.so.0        python2.7
libwx_gtk3u_gl-3.1.so.0.0.0    python3.5
libwx_gtk3u_html-3.1.so        wx
libwx_gtk3u_html-3.1.so.0 

I do think it contains all of files (development package or otherwise), since it was the only file offered for download from the wxWidgets.org website. I had installed gtk3-inicode-3.1. May this be an issue with gtk3? 

I would be very willing to try the tarball! My email is, dodson.bryan[AT]gmailDOTcom. 

Bryan

**Comment by brettbode** [comment]
Hi Byran,
   Those look like the normal libraries for a source install. You could apt-get install the wxGTK 3.0 system libraries to see if that works or I will try to roll up a tarball later today.

Brett

**Comment by dodsonbryan** [comment]
Hi Brett, 

I just downloaded and installed libwxgtk-3.0-dev and attempted another "make' command. Unfortunately, this has resulted in the same failure as previously noted. Perhaps the tarball would be best? I hope that it will make it work without these errors.

Bryan

**Comment by brettbode** [comment]
Hi Bryan,
   That has me worried a little... Let's try a the latest code. You can grab a tarball ready for source install at:
https://uofi.box.com/s/nzxagp9wokuyyynd5tnq06xzyysfad6t

Brett

**Comment by brettbode** [comment]
Ugh... hold off... I see an issue with the latest pull for 3.1.

**Comment by brettbode** [comment]
Ok. I fixed the build issue I ran into (not the one you reported) and it seems to build cleanly on a Debian Jessie against the latest wxWidgets package (3.1) built from source. Same link as before:
https://uofi.box.com/s/nzxagp9wokuyyynd5tnq06xzyysfad6t

Brett

**Comment by dodsonbryan** [comment]
Hi Brett,

Great news! The program now works and installs correctly on my system. If any more bugs come up past this point, I will certainly let you know. Thanks again for the excellent program!!

Bryan

**Comment by brettbode** [comment]
Great! I will mark this as fixed in the next release and close then. BTW the snapshot I provided includes some work in progress changes to add export to animated GIFs. That isn't complete so when I get it done and get the release out you should update to it.

Enjoy the program.
